name: traffic_light_color_detection

channels:
  - conda-forge
  - defaults

dependencies:
  - matplotlib
  - opencv
  - pandas
  - python=3.9.5
  - Pillow
  - jupyter
  - seaborn
  - scikit-learn
  - shapely
  - torchvision
  - tqdm
